### ISSUE TITLE
Unable to add platforms on new EKS install

### ISSUE THREAD

**Issue by mheadd** [tsuru/tsuru#2648] opened 2023-09-06 19:43 UTC
I'm having trouble with a new install of Tsuru. I'm following the [instructions here](https://docs.tsuru.io/main/installing/installing-gke.html) for installing on a Google Kubernetes Engine cluster with Helm, except I'm deploying to a cluster on Amazon EKS.

When I get to the step to install platforms, I run into an issue with images getting pushed to the `tsuru-registry`.

### Error message

Note - I've obscured the IP address of the `tsuru-registry` in the example below.

```
~$ tsuru platform add go
2023-09-06 15:27:34 -0400: ---- Building platform go on cluster local ----
2023-09-06 15:27:34 -0400:  ---> Destination image: {registry-ip}:80/tsuru/go:v1
2023-09-06 15:27:34 -0400:  ---> Destination image: {registry-ip}:80/tsuru/go:latest
2023-09-06 15:27:34 -0400: ---- Starting build ----
2023-09-06 15:27:34 -0400:  ---> go-image-build - Successfully assigned tsuru/go-image-build to ip-192-168-11-101.ec2.internal [default-scheduler]
2023-09-06 15:27:35 -0400:  ---> go-image-build - spec.containers{build-cont} - Container image "tsuru/deploy-agent:0.10.2" already present on machine [kubelet, ip-192-168-11-101.ec2.internal]
2023-09-06 15:27:35 -0400:  ---> go-image-build - spec.containers{build-cont} - Created container build-cont [kubelet, ip-192-168-11-101.ec2.internal]
2023-09-06 15:27:35 -0400:  ---> go-image-build - spec.containers{build-cont} - Started container build-cont [kubelet, ip-192-168-11-101.ec2.internal]
2023-09-06 15:27:37 -0400: Step 1/1 : FROM tsuru/go
2023-09-06 15:27:37 -0400: latest: Pulling from tsuru/go
2023-09-06 15:27:37 -0400: Digest: sha256:2b8c9277a846e686350c3ab5209f82336e477aa266a53923b494883e80dbf193
2023-09-06 15:27:37 -0400: Status: Image is up to date for tsuru/go:latest
2023-09-06 15:27:37 -0400:  ---> 85ebde38761f
2023-09-06 15:27:37 -0400: Successfully built 85ebde38761f
2023-09-06 15:27:37 -0400: Successfully tagged {registry-ip}:80/tsuru/go:v1
2023-09-06 15:27:37 -0400:  ---> Sending image to repository ({registry-ip}:80/tsuru/go:v1)
2023-09-06 15:27:37 -0400: The push refers to repository [{registry-ip}:80/tsuru/go]
2023-09-06 15:27:37 -0400: warning: log message lost due to parse error: Get "https://{registry-ip}:80/v2/": http: server gave HTTP response to HTTPS client
2023-09-06 15:27:37 -0400: Could not send image, trying again. Original error: Get "https://{registry-ip}:80/v2/": http: server gave HTTP response to HTTPS client
2023-09-06 15:27:38 -0400: The push refers to repository [{registry-ip}:80/tsuru/go]
2023-09-06 15:27:38 -0400: warning: log message lost due to parse error: Get "https://{registry-ip}:80/v2/": http: server gave HTTP response to HTTPS client
2023-09-06 15:27:38 -0400: Could not send image, trying again. Original error: Get "https://{registry-ip}:80/v2/": http: server gave HTTP response to HTTPS client
2023-09-06 15:27:39 -0400: The push refers to repository [{registry-ip}:80/tsuru/go]
2023-09-06 15:27:39 -0400: warning: log message lost due to parse error: Get "https://{registry-ip}:80/v2/": http: server gave HTTP response to HTTPS client
2023-09-06 15:27:39 -0400: Could not send image, trying again. Original error: Get "https://{registry-ip}:80/v2/": http: server gave HTTP response to HTTPS client
2023-09-06 15:27:40 -0400: [deploy-agent] error: failed to build image: error pushing image {registry-ip}:80/tsuru/go:v1: Error pushing image: Get "https://{registry-ip}:80/v2/": http: server gave HTTP response to HTTPS client ---> Cleaning up
Error: unexpected container "build-cont" termination: Exit 1 - Reason: "Error" - Message: "[deploy-agent] error: failed to build image: error pushing image {registry-ip}:80/tsuru/go:v1: Error pushing image: Get \"https://{registry-ip}:80/v2/\": http: server gave HTTP response to HTTPS client": invalid pod phase "Running" - last event: Started container build-cont
```

For some reason, the IP address of the `tsuru-registry` is appended with port 80, which seems to be what is causing the "server gave HTTP response to HTTPS client" error. 

### Things I've tried

I've tried changing the settings in the Helm chart (via `helm upgrade` to remove the trailing port number from the registry IP, but to no avail.

I've tried setting `tsuru-api.tsuruConfig.docker.registry=tsuru-registry:443` and `registry.service.port=443`, and though these change the kind of error I see, I am still unable to successfully add platforms. Nothing I have tried seems to remove the port number from the `tsuru-registry` IP address in my install.

Any suggestions on things I can change that would allow me to add platforms?

**Comment by wpjunior** [comment] 2023-09-06 19:55
Hi @mheadd we changed the engine recently to use the best of docker/buildkit instead of hijacking docker of k8s nodes.

we need to review the tutorial to work fine with new engine, in the next days or weeks I think that we will finished this.
I apologize for that situation.

**Comment by wpjunior** [comment] 2023-09-06 19:57
other thing that you may try is to provide de clusterIP of tsuru-registry and run a helm upgrade

**Comment by mheadd** [comment] 2023-09-21 13:46
Hi, @wpjunior - just wanted to circle back and see if there was a sense of when the install tutorial for Tsuru would be updated to reflect recent changes. Thanks!

**Comment by wpjunior** [comment] 2023-09-21 16:24
Hi @mheadd, we have updated 2 charts: 
https://github.com/tsuru/charts/tree/main/charts/tsuru-stack and https://github.com/tsuru/charts/tree/main/charts/tsuru-api

please update your helm and try again

thanks!

**Comment by eduardofg87** [comment] 2023-10-10 22:20
If the problem is solved, please close the issue. Thanks!

**Closed** 2023-10-11 14:44 UTC
