### ISSUE TITLE
installer: can't add node

### ISSUE THREAD

**Issue by guestisp** [tsuru/tsuru#1511] opened 2016-12-07 23:18 UTC
On Google Cloud, these are the latest lines when running `tsuru install`

```
Tsuru API successfully installed!
Bootstrapping Tsuru API...adding target
New target cloudster-test -> http://1.2.3.4:8080 added to target list and defined as the current target
log in with default user: admin@example.comPassword: 
Successfully logged in!
adding pool
Pool successfully registered.
creating node 1/3...
Error: Error bootstrapping tsuru: failed to create node: 404 page not found
```

**Comment by andrestc** [comment] 2016-12-07 23:22
Hi @guestisp, thanks for reporting this. I think you are facing the same [issue described here](https://github.com/tsuru/tsuru/issues/1497). Take a look at [my answer](https://github.com/tsuru/tsuru/issues/1497#issuecomment-261744005) and see if that fix it for you.

**Comment by guestisp** [comment] 2016-12-07 23:24
Trying right now... let's see...

**Comment by guestisp** [comment] 2016-12-07 23:33
It doesn't work:

```
Error: Error bootstrapping tsuru: failed to create node: Instructions:
DockerMachine IaaS required params:
  driver=<driver>                         Driver to be used by docker machine. Can be set on the IaaS configuration.

Optional params:
  name=<name>                             Hostname for the created machine
  docker-install-url=<docker-install-url> Remote script to be used for docker installation. Defaults to: http://get.docker.com. Can be set on the IaaS configuration.
  insecure-registry=<insecure-registry>   Registry to be added as insecure-registry to the docker engine. Can be set on the IaaS configuration.
  docker-flags=<flag1,flag2>              Arbitrary docker engine flags. Can be set on the IaaS configuration.
: multiple errors reported (2):
error #0: Error with pre-create check: "Project with ID \"myproject-test\" not found. googleapi: Error 403: Insufficient Permission, insufficientPermissions"
failed to create host
```


```
hosts:
  core:
    size: 1
    driver:
       options:
          google-zone: europe-west1-d
  apps:
    size: 3
    dedicated: true
    driver:
       options:
          google-zone: [europe-west1-d, us-east1-d, us-central1-f]
          google-machine-type: n1-standard-2
driver:
  name: google
  options:
    google-project: myproject-test
    google-machine-type: n1-standard-1
components:
    tsuru:
        version: latest
```

**Comment by andrestc** [comment] 2016-12-07 23:42
Seems like you had some kind of permission problem when creating the node: 

```
"Project with ID \"myproject-test\" not found. googleapi: Error 403: Insufficient Permission, insufficientPermissions"
```

Can you ssh into your core host and do a `docker inspect` on the api container? I would like to check how the `IAAS_CONF` env is set.

I'll try getting access to an google cloud engine account in the following days so I can try debugging it.

**Comment by andrestc** [comment] 2016-12-07 23:45
Any chance your are configuring your google cloud credentials thru environment variables? These wont work since they need to be on the config file (to be sent over to the api so it can configure it's iaas). This should probably be added to the docs.

**Comment by guestisp** [comment] 2016-12-07 23:47
I've not configured any google credentials. The whole tsuru.cnf file was posted above and i've not configured anything else.

```
[
    {
        "Id": "38b9cfe00866474b5b49a88c58018b440e22546a9013ca2b7f55b0b5467f981c",
        "Created": "2016-12-07T23:31:04.073480243Z",
        "Path": "/bin/tsurud",
        "Args": [
            "api"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 25529,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2016-12-07T23:31:04.627385619Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:7b08cf174c8542095e86765688cfe4f5743ee6603d94ee778b90047ebea6a8c6",
        "ResolvConfPath": "/var/lib/docker/containers/38b9cfe00866474b5b49a88c58018b440e22546a9013ca2b7f55b0b5467f981c/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/38b9cfe00866474b5b49a88c58018b440e22546a9013ca2b7f55b0b5467f981c/hostname",
        "HostsPath": "/var/lib/docker/containers/38b9cfe00866474b5b49a88c58018b440e22546a9013ca2b7f55b0b5467f981c/hosts",
        "LogPath": "/var/lib/docker/containers/38b9cfe00866474b5b49a88c58018b440e22546a9013ca2b7f55b0b5467f981c/38b9cfe00866474b5b49a88c58018b440e22546a9013ca2b7f55b0b5467f981c-json.log",
        "Name": "/tsuru.1.5kk75ea9fqelo9wq9nz58vj6n",
        "RestartCount": 0,
        "Driver": "aufs",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/etc/docker/certs.d:/certs:ro"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": null,
            "RestartPolicy": {
                "Name": "",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": -1,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0
        },
        "GraphDriver": {
            "Name": "aufs",
            "Data": null
        },
        "Mounts": [
            {
                "Source": "/etc/docker/certs.d",
                "Destination": "/certs",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "38b9cfe00866",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "8080/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "MONGODB_ADDR=mongo",
                "MONGODB_PORT=27017",
                "REDIS_ADDR=redis",
                "REDIS_PORT=6379",
                "HIPACHE_DOMAIN=1.1.1.1.nip.io",
                "REGISTRY_ADDR=10.132.0.2",
                "REGISTRY_PORT=5000",
                "TSURU_ADDR=http://1.1.1.1",
                "TSURU_PORT=8080",
                "IAAS_CONF={\"dockermachine\":{\"ca-path\":\"/certs\",\"driver\":{\"name\":\"google\",\"options\":{\"google-machine-type\":\"n1-standard-1\",\"google-project\":\"myproject-test\"}}}}",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": null,
            "Image": "tsuru/api:latest",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": [
                "/bin/tsurud",
                "api"
            ],
            "OnBuild": null,
            "Labels": {
                "com.docker.swarm.node.id": "00dvjfhovzg94gg61r1i9q3id",
                "com.docker.swarm.service.id": "5ai8k0eb2xn6ofv8t3bs98yyh",
                "com.docker.swarm.service.name": "tsuru",
                "com.docker.swarm.task": "",
                "com.docker.swarm.task.id": "5kk75ea9fqelo9wq9nz58vj6n",
                "com.docker.swarm.task.name": "tsuru.1"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "adacdd2f167b8ec226ef5944cf3cd4a5b8a32998cbe52a98719986f0d1ea648b",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "8080/tcp": null
            },
            "SandboxKey": "/var/run/docker/netns/adacdd2f167b",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "ingress": {
                    "IPAMConfig": {
                        "IPv4Address": "10.255.0.9"
                    },
                    "Links": null,
                    "Aliases": [
                        "38b9cfe00866"
                    ],
                    "NetworkID": "19qhk3jxcrx1oaclr6xvny9uy",
                    "EndpointID": "5e446740e0e6301b9eb0b092010b3b9876cb11057e52584356e0f9df86453b6e",
                    "Gateway": "",
                    "IPAddress": "10.255.0.9",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:0a:ff:00:09"
                },
                "tsuru": {
                    "IPAMConfig": {
                        "IPv4Address": "10.0.9.11"
                    },
                    "Links": null,
                    "Aliases": [
                        "38b9cfe00866"
                    ],
                    "NetworkID": "1rqs26rvcad0itugcya0rtdqf",
                    "EndpointID": "06e658fcf8437a6363579686acd3155218b3401cdd548fe2788736706f1b4367",
                    "Gateway": "",
                    "IPAddress": "10.0.9.11",
                    "IPPrefixLen": 24,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:0a:00:09:0b"
                }
            }
        }
    }
]
```

**Comment by andrestc** [comment] 2016-12-08 12:24
It seems that the `google` driver uses the default gce client, that looks for [some .json file with the credentials](https://github.com/docker/machine/blob/bf08cd61adc629def838220ee5f069f6f2f8591a/vendor/golang.org/x/oauth2/google/default.go#L60). You probably have this file somewhere on your machine and the local google driver is able to use it.

The problem is that to be able to create the application nodes, the docker-machine iaas runs the driver in the api container and this file wont be available there.

I think the installer should provide a way to create the application machines from the local driver, instead of using the docker-machine iaas as a fallback for situations like this one. We can also check if we can PR a change to the docker/machine google driver to be able to set the credentials directy, but I think thats not the usual gce way.

**Comment by guestisp** [comment] 2016-12-08 21:47
So, currently, is not possible to use docker-machine with Google ?

**Comment by guestisp** [comment] 2016-12-09 08:18
Another (maybe much easier) solution could be to copy the local json file used by docker-machine (it should be here: `$HOME/.config/gcloud/application_default_credentials.json` to the API controller

**Comment by andrestc** [comment] 2016-12-09 12:50
On amazon you can use `amazonec2-access-key` and `amazonec2-secret-key` which do not auto expire.

A quick and temporary fix would be to do the same as the `virtualbox` driver [here](https://github.com/tsuru/tsuru-client/blob/master/tsuru/installer/installer.go#L103), using the local driver to create the nodes and registering them on the API. This would fix the installer but the docker-machine iaas configuration would still not work on this setup (so no autoscaling and healing as your said).

The google client also checks if we are on GCE and has a way to fetch the credentials from a [metadata server](https://github.com/docker/machine/blob/bf08cd61adc629def838220ee5f069f6f2f8591a/vendor/golang.org/x/oauth2/google/default.go#L93), this should work from the api (and would fix all the issues). Maybe that can help you debug this? I'll also try to get access to a GCE account to help you.

**Comment by guestisp** [comment] 2016-12-09 13:18
I'm new on GCE and I'm not sure on how to use the metadata server.
Probably, making tsuru able to refresh the oAuth token would be the best thing.

**Comment by guestisp** [comment] 2016-12-09 13:22
Anyway, docker-machine is already able to use the metadata server as source for credential, but in my case this doesn't work, so something else should be configured, i don't think it's "plug&play"

Anyway, let me try to check if the following is returning the access token like wrote on google docs

```
curl "http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token" \
-H "Metadata-Flavor: Google"
```

**Comment by guestisp** [comment] 2016-12-09 13:26
It worked.

```
{"access_token":"x","expires_in":3599,"token_type":"Bearer"}
```

but tsuru is unable to add nodes

**Comment by andrestc** [comment] 2016-12-09 13:36
Could you try running `curl` from inside the api container? Go to the host where the api is running, get the container name and do:

```
docker exec -it <container-name> apk add --update curl && curl "http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token" -H "Metadata-Flavor: Google"
```

**Comment by guestisp** [comment] 2016-12-09 14:39
It worked:

```
{"access_token":"x","expires_in":3599,"token_type":"Bearer"}
```

**Comment by guestisp** [comment] 2016-12-09 16:51
This is strange. From Docker I'm able to get the token but tsuru isn't able to create nodes

**Comment by guestisp** [comment] 2016-12-10 11:03
Should I configure the `iaas` in tsuru.conf ? Because I've not set that, the `tsuru.conf` is created automatically by the installer.

**Comment by andrestc** [comment] 2016-12-10 12:55
that config is done by the environment variable IAAS_CONF on the tsuru api container. It is correctly configured since it was able to try to create the node using your project id(set on the conf).

I'll be able to test the installer on google on the next few days. I can only guess now but I'm suspicious that the docker-machine google driver is not fetching the credentials from the metadata server correctly. I would try installing docker-machine on a vm at gce and try creating another machine from it.

**Comment by guestisp** [comment] 2016-12-10 13:05
> I would try installing docker-machine on a vm at gce and try creating another machine from it.

Is what i'm trying to do right now. I've installed tsuru from Ubuntu but there isn't any dockermachine support, so i'm trying to build from scratch

**Comment by guestisp** [comment] 2016-12-10 13:37
tsurud running from sources, but i'm still hitting the same issue:

`error #0: Error with pre-create check: "Project with ID \"x\" not found. googleapi: Error 403: Insufficient Permission, insufficientPermissions"`

but:

```
$ curl "http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token" -H "Metadata-Flavor: Google" && echo
{"access_token":"x","expires_in":3461,"token_type":"Bearer"}
```

So, the api controller (this time is not a docker container) is able to access to metadata server, but docker-machine don't

**Comment by andrestc** [comment] 2016-12-10 14:19
I think you need to configure your instance to properly be able to issue commands to the google api from inside it.

Take a look at https://groups.google.com/forum/#!topic/gce-discussion/f0PW-bGEWvk and https://cloud.google.com/compute/docs/access/create-enable-service-accounts-for-instances?hl=en_US

**Comment by andrestc** [comment] 2016-12-10 14:24
Looking at the google driver, the machine is created with some [default scopes](https://github.com/docker/machine/blob/735741f76f5a189ed1edfa5dd40f2e03201a9511/drivers/google/google.go#L40). 

I think we need to figure out what scopes are needed to create a new instance and run the installer with the `google-scopes` configured with the needed scopes. This should be added automatically on the installer (and documented).

**Comment by ArxdSilva** [comment] 2017-01-05 18:20
@guestisp I was able to reproduce your problem, It seams that the installer needs to provision a few API permissions before creating any node. 

For now we're doing it on .yml file but It'll be automatic soon in the installer.

**Comment by ArxdSilva** [comment] 2017-01-09 18:30
@guestisp we have solved this [here](https://github.com/tsuru/tsuru-client/commit/950231d43a0a4e1fc655318cc120765163d4508f), could you check If It's working for you?

**Comment by ArxdSilva** [comment] 2017-01-23 16:38
@guestisp closing since we got no feedback, If you get any other issue related or want to discuss we can reopen

**Closed by ArxdSilva** 2017-01-23 16:38 UTC

**Comment by guestisp** [comment] 2017-04-25 14:45
I'm sorry for this, i've missed the update.
I'll try ASAP
